# Generated by Django 5.2.3 on 2025-09-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_post_cerated_at'),
    ]

    operations = [
    ]
