# Generated by Django 5.2.3 on 2025-09-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_categary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.categary'),
            preserve_default=False,
        ),
    ]
