# Generated by Django 5.2.6 on 2026-03-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_post_categary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categary',
            old_name='name',
            new_name='names',
        ),
    ]
